# Generated by Django 5.0.4 on 2024-05-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositions',
            name='player1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player5',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
