# Generated by Django 5.0.4 on 2024-05-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_compositions_player1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositions',
            name='player10',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player11',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player12',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player13',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player14',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player15',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player16',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player17',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player18',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player19',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player20',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player21',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player22',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player23',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player24',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player25',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player7',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player8',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player9',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
