# Generated by Django 5.0.4 on 2024-05-27 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_compositions_player10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='away_score',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='matches',
            name='home_score',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
