# Generated by Django 5.0.4 on 2024-05-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_matches_away_score_alter_matches_home_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='precipitation',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='pressure',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='weather_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='wind_speed',
            field=models.FloatField(null=True),
        ),
    ]
