# Generated by Django 5.0.4 on 2024-05-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_matches_humidity_alter_matches_precipitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositions',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player1', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player10', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player11', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player12', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player13', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player14', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player15', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player16', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player17', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player18', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player19', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player2', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player20', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player21', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player22', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player23', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player24', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player25', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player3', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player4', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player5', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player6', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player7', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player8', to='website.players'),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='player9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compo_player9', to='website.players'),
        ),
    ]
