# Generated by Django 5.0.4 on 2024-05-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_compositions_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='url',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
