# Generated by Django 5.0.4 on 2024-05-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_players_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rankings',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='rankings',
            constraint=models.UniqueConstraint(fields=('competition', 'pool', 'year', 'locale', 'rank'), name='cle_primaire'),
        ),
    ]
