# Generated by Django 5.0.4 on 2024-05-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_ranks_ranks_cle_primaire_rank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ranks',
        ),
    ]
