# Generated by Django 5.0.4 on 2024-05-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_delete_ranks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankings',
            options={'managed': False},
        ),
    ]
