# Generated by Django 5.0.4 on 2024-05-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_rankings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compositions',
            options={'managed': False},
        ),
    ]
