# Generated by Django 5.0.4 on 2024-05-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_compositions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compositions',
            options={},
        ),
    ]
