# Generated by Django 5.0.4 on 2024-05-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_compositions_comp_id_alter_compositions_key_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositions',
            name='comp_id',
            field=models.CharField(max_length=600, primary_key=True, serialize=False),
        ),
    ]
