# Generated by Django 5.0.4 on 2024-05-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_compositions_comp_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankings',
            options={},
        ),
    ]
