# Generated by Django 5.0.4 on 2024-05-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_rankings_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankings',
            name='id',
        ),
        migrations.AddField(
            model_name='rankings',
            name='ranking_id',
            field=models.CharField(default=None, max_length=200, primary_key=True, serialize=False),
        ),
    ]
