# Generated by Django 5.0.4 on 2024-05-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_rankings_ranking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odds',
            name='away_odds',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='odds',
            name='draw_odds',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='odds',
            name='home_odds',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='odds',
            name='probable_score_diff',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='odds',
            name='total_point',
            field=models.FloatField(null=True),
        ),
    ]
