# Generated by Django 5.0.4 on 2024-06-26 13:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_odds_away_odds_alter_odds_draw_odds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='substitution',
            fields=[
                ('sub_id', models.CharField(max_length=600, primary_key=True, serialize=False)),
                ('key_id', models.SlugField(max_length=600, null=True)),
                ('local_team', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)])),
                ('sub_time1', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)])),
                ('sub_time2', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)])),
                ('sub_time3', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)])),
                ('sub_time4', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)])),
                ('sub_time5', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)])),
                ('sub_time6', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)])),
                ('sub_time7', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)])),
                ('sub_time8', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)])),
                ('sub_time9', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)])),
                ('sub_time10', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)])),
                ('sub_time11', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)])),
                ('sub_time12', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)])),
                ('player_in1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_in1', to='website.players')),
                ('player_in10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_in10', to='website.players')),
                ('player_in11', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_in11', to='website.players')),
                ('player_in12', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_in12', to='website.players')),
                ('player_in2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_in2', to='website.players')),
                ('player_in3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_in3', to='website.players')),
                ('player_in4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_in4', to='website.players')),
                ('player_in5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_in5', to='website.players')),
                ('player_in6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_in6', to='website.players')),
                ('player_in7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_in7', to='website.players')),
                ('player_in8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_in8', to='website.players')),
                ('player_in9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_in9', to='website.players')),
                ('player_out1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_out1', to='website.players')),
                ('player_out10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_out10', to='website.players')),
                ('player_out11', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_out11', to='website.players')),
                ('player_out12', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_out12', to='website.players')),
                ('player_out2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_out2', to='website.players')),
                ('player_out3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_out3', to='website.players')),
                ('player_out4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_out4', to='website.players')),
                ('player_out5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_out5', to='website.players')),
                ('player_out6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_out6', to='website.players')),
                ('player_out7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_out7', to='website.players')),
                ('player_out8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_out8', to='website.players')),
                ('player_out9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_out9', to='website.players')),
            ],
        ),
    ]
