# Generated by Django 5.0.4 on 2024-05-23 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tchats',
            fields=[
                ('tchat_category', models.CharField(max_length=100, null=True)),
                ('slug_tchat_category', models.SlugField(blank=True, max_length=600, null=True)),
                ('tchat_name', models.CharField(max_length=100, null=True)),
                ('slug_tchat_name', models.SlugField(max_length=600, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'tchats',
            },
        ),
        migrations.CreateModel(
            name='threads_categories_match',
            fields=[
                ('thread_league', models.CharField(max_length=100, null=True)),
                ('slug_thread_league', models.SlugField(max_length=600, primary_key=True, serialize=False)),
                ('thread_category', models.CharField(max_length=100, null=True)),
                ('slug_thread_category', models.SlugField(max_length=600, null=True)),
            ],
            options={
                'verbose_name_plural': 'threads_categories_match',
            },
        ),
        migrations.CreateModel(
            name='tchat_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tchat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fora.tchats')),
            ],
            options={
                'verbose_name_plural': 'tchat_posts',
            },
        ),
        migrations.CreateModel(
            name='threads_match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fora.threads_categories_match')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.matches')),
            ],
        ),
        migrations.CreateModel(
            name='threads_comments_match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fora.threads_match')),
            ],
        ),
    ]
