# Generated by Django 5.0.4 on 2024-05-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fora', '0002_alter_threads_categories_match_slug_thread_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tchats',
            name='slug_tchat_name',
            field=models.SlugField(blank=True, max_length=600, primary_key=True, serialize=False),
        ),
    ]
