# Generated by Django 5.0.4 on 2024-07-23 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fora', '0003_alter_tchats_slug_tchat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='thread_match',
            fields=[
                ('key_id', models.SlugField(max_length=600, primary_key=True, serialize=False)),
                ('closed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fora.threads_categories_match')),
            ],
        ),
    ]
