# Generated by Django 5.0.4 on 2024-07-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fora', '0005_alter_threads_comments_match_thread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='threads_match',
        ),
    ]
