# Generated by Django 5.0.4 on 2024-07-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fora', '0006_delete_threads_match'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='thread_match',
            new_name='threads_match',
        ),
        migrations.AlterModelOptions(
            name='threads_comments_match',
            options={'verbose_name_plural': 'threads_comments_match'},
        ),
    ]
