# Generated by Django 5.0.4 on 2024-06-26 13:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0021_substitution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='predictions_matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_margin1', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(3)])),
                ('prediction_margin2', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(3)])),
                ('prediction_total1', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(3)])),
                ('prediction_total2', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(3)])),
                ('prediction_match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.matches')),
                ('user_prediction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
